export const eng = {
  code: "en",
  name: "English",
  switchLabel: "FR",
  switchAria: "Switch language to French",
  nav: {
    home: "Home",
    about: "About",
    experience: "Experience",
    projects: "Projects",
    skills: "Skills",
    education: "Education",
    certifications: "Certifications",
    contact: "Contact",
    cta: "Let's Talk",
  },
  hero: {
    titleBefore: "I build",
    titleHighlight: "intelligent software",
    titleAfter: "that connects AI with real-world applications.",
    description: "Software Engineer specializing in Full-Stack development and Artificial Intelligence, with hands-on experience building intelligent web platforms, AI-powered APIs, Computer Vision systems, Generative AI solutions, and conversational agents.",
    explore: "Explore My Work",
    contact: "Contact Me",
    linkedin: "LinkedIn Profile",
    resume: "Download Resume",
  },
  projects: {
    eyebrow: "Selected Work",
    title: "Engineering projects built around AI, systems, and usable products.",
    description: "A cleaner view of Mohamed's strongest work, grouped by technical focus and designed for quick comparison.",
    featured: "Featured",
    more: "more",
    fallbackSubtitle: "AI & Full-Stack Platform",
    modal: {
      close: "Close project modal",
      zoom: "Zoom Screenshot",
      closeZoom: "Close zoom",
      organization: "Organization:",
      timeline: "Timeline:",
      descriptionTitle: "Project Description & Solution",
      stack: "Technology Stack",
    },
  },
  experience: {
    title: "Work Experience",
    project: "Project:",
  },
  skills: {
    title: "Technical Expertise",
    description: "A comprehensive mapping of full-stack engineering practices, machine learning pipelines, and advanced artificial intelligence toolkits.",
    categories: {
      programming: "Programming Languages",
      frontend_backend: "Frontend & Backend Frameworks",
      databases: "Databases & Design",
      machine_learning: "Machine Learning & Analysis",
      deep_learning_computer_vision: "Deep Learning & Computer Vision",
      generative_ai: "Generative AI & Agents",
      backend_api: "APIs & Integration",
      devops: "DevOps & Tools",
    },
  },
  education: {
    title: "Education & Background",
    classOf: "Class of",
    specialization: "Specialization:",
  },
  certifications: {
    title: "Licenses & Certifications",
    description: "Professional development, industry-recognized certificates, and credentials specialized in AI development, LangGraph, and RAG.",
    issued: "Issued",
    verify: "Verify",
  },
  contact: {
    titleStart: "Let's Build",
    titleHighlight: "Something Intelligent.",
    description: "Interested in Software Engineering, Artificial Intelligence, Full-Stack development, or innovative AI agents and computer vision systems? Let's connect and discuss opportunities.",
    email: "Email Me",
    phone: "Call Me",
    location: "Location",
  },
  footer: {
    rights: "All rights reserved.",
    scrollTop: "Scroll to top",
    linkedinAria: "Visit Mohamed's LinkedIn profile",
    emailAria: "Send Mohamed an email",
  },
  chatbot: {
    languageInstruction: "The portfolio language currently selected is English. Always respond in English, even if the visitor mixes languages.",
    initialMessage: "Hello! I am Mohamed's AI Assistant. Ask me anything about his projects, experience, technical skills, or availability!",
    errorMessage: "Sorry, I had trouble connecting to my cognitive models. Please try again in a few seconds or contact Mohamed directly.",
    invite: "Ask my AI Agent!",
    toggleAria: "Toggle AI assistant",
    title: "Mohamed's AI Assistant",
    status: "Online",
    thinking: "Assistant is thinking...",
    suggested: "Suggested questions:",
    placeholder: "Ask about my projects, stack...",
    sendAria: "Send message",
    presetQuestions: [
      "Tell me about AutoDispatch project.",
      "What are Mohamed's AI & RAG skills?",
      "Is he available for job offers?",
      "Show me his certifications.",
    ],
  },
};
